name: AltarCrafting
version: 1.0
api-version: 1.19
main: me.Sebbben.AltarCrafting.Main
commands:
  altarCrafting:
    description: Main command for the altarcrafting plugin
    usage: /<command> args
    aliases:
      - ac
      - alCr
      - altarCraft